### ISSUE TITLE
config parameter

### ISSUE THREAD

**Issue by vinson2233** [Deepest-Project/MelNet#29]
Hi, I wanted to train the MelNet with my own dataset.  
There are some audio setting that I still not understand since I'm very new to this signal processing/speech field. Can someone elaborate me or give me reference for me to understand what are the meaning of these setting :
```
audio:
  sr: 16000
  duration: 6.0
  n_mels: 180
  hop_length: 180
  win_length: 1080
  n_fft: 1080
  num_freq: 541
  ref_level_db: 20.0
  min_level_db: -80.0
```

Thanks in advance
